# Generated by Django 4.1.7 on 2023-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_api", "0004_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="av_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
