# Generated by Django 4.2.5 on 2023-10-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "RESTAURANT"), (2, "CUSTOMER")], null=True
            ),
        ),
    ]
