# Generated by Django 4.2.5 on 2023-10-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "VENDOR"), (2, "CUSTOMER")], null=True
            ),
        ),
    ]
