# Generated by Django 4.2.5 on 2023-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dipeat_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_profile",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user_profile",
            old_name="Last_name",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="Phone_no",
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
